name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  ts-check:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - uses: ./ts.yml
  lint:
    needs: [ts-check]
    runs-on: ubuntu-latest
    steps:
      - uses: ./lint.yml
