name: Main Workflow

on:
  push:
    branches:
      - main

jobs:
  ts-check:
    needs: []
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/ts.yml
  lint:
    needs: [ts-check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/lint.yml
